### ISSUE TITLE
Fails when using with Vagrant NFS in another project

### ISSUE THREAD

**Issue by kusmierz** [adlogix/docker-machine-nfs#6]
I've got an error:

``` bash
[INFO] Configure NFS ... 

 !!! Sudo will be necessary for editing /etc/exports !!! 
exports:5: /Users conflicts with existing export /Users/adam/Projects/my-project
```

**Comment by silvamerica** [comment]
The directory path model for Docker Machine is in conflict with Vagrant's. It's not really a problem that this script can address (other than making a better warning message). I solved this by reprovisioning my Vagrant VM to use the Docker model. Now the entire /Users directory gets shared into the Vagrant VM. I then created a shell provisioner in my Vagrantfile that creates a symlink to keep all of my paths the same as they were before. If you don't care about the paths being exactly the same, you can just adapt to the new paths.

**Comment by tonivdv** [comment]
Hey @kusmierz ,

In addition to @silvamerica (btw thanks for the explanation) this script has /Users as hardcoded shared directory. If you want your docker-machine box to share a different directory, you'll (currently) have to change that manually in the script file. However, keep in mind that you will not be able to use commands like 'docker run -v $(pwd):/src' ... because your host path will not match your virtual machine path. (This is I guess one of the reasons that docker-machine by default shares /Users)

Hope this helps.
